### ISSUE TITLE
Hotkey Support with Optional Modifier

### ISSUE THREAD

**Issue by Ops226** [Azuna1/gw2co-documentation#13]
Bind a key with a modifier or without to a Lua function.
ex) Bind key CTRL + mouse left-click to Player:Teleport(Vector3 Pos)

**Comment by blunderbusterboi** [comment]
Additionally could this be used to interact with windows when gw2co menu is hidden?

**Comment by Azuna1** [comment]
since you would just bond hotkeys to lua functions. and the fact that you create the UI within your code, you can do whatever you like in those functions modifiyng your ui etc
