### ISSUE TITLE
Double GUI.

### ISSUE THREAD

**Issue by Weaver111** [Azuna1/gw2co-documentation#25]
**What is the Issue?`**
Double GUI.

**Describe what exactly is not working**
There are 2 GUI. It looks like 1 is a magnifying glass.

**How to reproduce the issue:**
- Start the game manually
- Run ''startmyfriend'' at character selection.

**Additional wishes / information**
It looks like 1 is a magnifying glass. You cant type in the bigger one.

![Naamloos](https://user-images.githubusercontent.com/78567970/153868514-fa807fc8-8d47-4dc2-94b0-c7514aa3e205.png)

**Comment by Azuna1** [comment]
#6 
;)
