### ISSUE TITLE
Game crashes on current build

### ISSUE THREAD

**Issue by lazaraslong** [Azuna1/gw2co-documentation#29]
What is the Issue?`
The game crashes on current build cause they updated
on sample esp script
Describe what exactly is not working
Sample ESP script doesn't load and when you press reload esp then it crashes

How to reproduce the issue:
Press reload ESP once loaded in and injected

Additional wishes / information
If possible could you add a build check where it won't inject and instead prompts a message to wait for an update if the game build has been changed?

**Comment by Azuna1** [comment]
its not possible to not inject if update is needed, but i added a version check after login and if an update is needed, gw2co wont do anything
