### ISSUE TITLE
Fishing at Pools doesn't work properly

### ISSUE THREAD

**Issue by DatHacksGaming** [Azuna1/gw2co-documentation#35]
Tested fishing at the following locations with different settings for the last coordinate. Tried setting Z to 40, 41, 42, 0 bi change.
I did notice manually casting into the pool caught the fish using the script but letting it cast automatically only returned "Open Water" fish. I only tested this for about 2 days so it could be "poor luck" but all the fish caught were Open Water I only caught 3 Offshore Fish and they were all manually done.

Tested with 500 baits (2 stacks, all Open Water)

The other types are listed below.
"Off Shore" 
"Shore Fish" 
"Cavern Fish" 
"Quarry Fish" 

Fish type can be checked in the Item Collection, Achievements > End of Dragons > Fishing > Seitung Province Fisher

Player:UseSkillbarSkillAoE(5,66975,Detail.Vector3(-916,-15557,41)) --(isle of reflection)
Player:UseSkillbarSkillAoE(5,66975,Detail.Vector3(1958,-5180,41)) --(isle of reflection)
Player:UseSkillbarSkillAoE(5,66975,Detail.Vector3(27742,-11482,41)) 

Player:UseSkillbarSkillAoE(5,66975,Detail.Vector3(30789,-27046,41)) --wreck, Shing Jea Island
Player:UseSkillbarSkillAoE(5,66975,Detail.Vector3(31785.937500,-27761.861328,41)) --offshore, Shing Jea Island
Player:UseSkillbarSkillAoE(5,66975,Detail.Vector3(-3078,-11353,41)) --offshore
Player:UseSkillbarSkillAoE(5,66975,Detail.Vector3(511,-11369,41)) --offshore Isle of reflection

**Comment by Azuna1** [comment]
i Rechecked packets, Z should be 0 inside isle of reflection at least
it will then also show the bobber, 
i just watched my testscript catch this:
![image](https://user-images.githubusercontent.com/2217585/159157974-0cddbaf3-63c9-4864-a71b-79d1dbe252b9.png)

**Comment by DatHacksGaming** [comment]
I had z0 for awhile I was wondering if that was the correct one, noticed the "MousePos" showed 0 when you put the mouse on where the water and boat meet I'll check it more to be safe :). Did about 3000 fish yesterday haha.

**Comment by Azuna1** [comment]
was this solved for you?

**Comment by DatHacksGaming** [comment]
Everything else seems to be working fine now, I think it's good to close. I got Player:UseSkillbarSkillAoE working fine with the Mechanist ACR I'm working on, but for some reason the fishing one below never casts the skill for me. Not sure if thats something with the z packet still or just me having some odd issue. It catches fish fine now just have to manually cast the aoe once to select the hole from there it fishes from that location without recasting ever lol.

	if(ImGui:Button("Casting",ImGui.ImVec2(60,20))) then
		myAgent = Detail:GetAgentById(Detail:GetOwnId())   
                Player:UseSkillbarSkillAoE(5,66975,Detail.Vector3(-907,-15518,0)) --waterfall
		info("Casting")
	end

**Comment by Azuna1** [comment]
The issue here was, if you level your fishing mastery you get a different fishing skill
in this case the id 67276
