### ISSUE TITLE
Frequent Crashes with new

### ISSUE THREAD

**Issue by DatHacksGaming** [Azuna1/gw2co-documentation#37]
I've noticed going into the Guild House Isle of Reflection is a roll of the dice sometimes it loads others it crashes. Issue only started after the most recent GW2CO update to add in the script manager.

![image](https://user-images.githubusercontent.com/20995515/160269637-b57b7379-0b2c-45ce-8d78-e4c1719a828a.png)

Disabled ArcDPS and other addons to ensure it wasn't them. Have tested from Seitung Province and going using Guild menu to  go to guild hall I've crashed 5 times in a row this evening but without the gw2co loaded I can enter no problem.

**Comment by DatHacksGaming** [comment]
This particular crash seems to be related to the game crashing if you try to teleport to a "contested waypoint" while gw2co is loaded. If loaded and you try to teleport to a contested waypoint it'll crash everytime.

**Comment by DatHacksGaming** [comment]
rechecked everything I can think of from drivers, to windows update, to loading the game without any addons (works fine) to running with ArcDPS without issue. Only seeing crashes teleporting to the guild house with gw2co loaded. Attached full log as well.

tested with the older dll prior from March 18th and it works perfectly so definitely something with the new version.


Mar 27 19:04:44 arcdps 20220316.171835-416-x64
Mar 27 19:04:45 info: gw2 0x7FF60A1E0000-0x7FF60CA9C000 (0xFAF8AB5A)
Mar 27 19:04:45 info: arcdps 0x7FFCC9160000-0x7FFCC92A9000 (0xBF9609AE)
Mar 27 19:04:45 info: chainloading d3d9
Mar 27 19:04:45 info: loading config from "C:\Program Files\Guild Wars 2\addons\arcdps\arcdps.ini"
Mar 27 19:04:46 info: ready
Mar 27 19:04:55 info: client closing
Mar 27 19:05:21 error: intercepted gw2 assertion fail
Mar 27 19:05:21 error: assertion: "D:\Perforce\Live\NAEU\v2\Code\Gw2\Engine\Text\TextApi.cpp", "CParser::Validate(buffer->Ptr(), buffer->Term(), true ) == buffer->Term()", 678
Mar 27 19:05:31 error: assertion: "D:\Perforce\Live\NAEU\v2\Code\Gw2\Engine\Text\TextApi.cpp", "CParser::Validate(buffer->Ptr(), buffer->Term(), true ) == buffer->Term()", 678
Mar 27 19:05:31 error: intercepted gw2 assertion fail
Mar 27 19:05:31 error: assertion: "D:\Perforce\Live\NAEU\v2\Code\Gw2\Engine\Text\TextApi.cpp", "CParser::Validate(buffer->Ptr(), buffer->Term(), true ) == buffer->Term()", 678
Mar 27 19:05:
[arcdps_lastcrash.log](https://github.com/Azuna1/gw2co-documentation/files/8359159/arcdps_lastcrash.log)
33 error: intercepted hardware exception at "C:\WINDOWS\System32\KERNELBASE.dll +0x0000000000034F69" thread 11484
Mar 27 19:05:33 info: --- exception ---
			code: 0x00000000E06D7363
			addr: 0x00007FFCF4CF4F69
			offs: 0x0000000000034F69
			prms:   0000000000000004
			flgs: 0x0000000000000001
Mar 27 19:05:33 info: --- system ---
			windows: 10.0
			cpu: Intel(R) Core(TM) i9-9900KF CPU @ 3.60GHz
			ram: 7889MB / 32702MB used
			gpu: NVIDIA GeForce RTX 2080


Mar 27 19:05:33 info: --- trace ---
			ep 0x7FFCF4CF4F69 frame 0x00D5889FEF40 rva 0x000000034F69 in KERNELBASE
			ep 0x7FFCE0756220 frame 0x00D5889FEFA0 rva 0x000000006220 in VCRUNTIME140
			ep 0x7FFCB0FBE242 frame 0x00D5889FEFF0 rva 0x00000007E242 in gw2co
			ep 0x7FFCB0FC094B frame 0x00D5889FF110 rva 0x00000008094B in gw2co
			ep 0x7FFCB0FBF071 frame 0x00D5889FF200 rva 0x00000007F071 in gw2co
			ep 0x7FFCB0FBE9A3 frame 0x00D5889FF240 rva 0x00000007E9A3 in gw2co
			ep 0x7FFCB0F496DA frame 0x00D5889FF2C0 rva 0x0000000096DA in gw2co
			ep 0x7FFCB0F5B76E frame 0x00D5889FF2F0 rva 0x00000001B76E in gw2co
			ep 0x7FF60B0188AB frame 0x00D5889FF7C0 rva 0x000000E388AB in Gw2-64
			ep 0x7FF60A5CA611 frame 0x00D5889FF830 rva 0x0000003EA611 in Gw2-64
			ep 0x7FF60A5CA850 frame 0x00D5889FF9F0 rva 0x0000003EA850 in Gw2-64
			ep 0x7FF60A5CB215 frame 0x00D5889FFA50 rva 0x0000003EB215 in Gw2-64
			ep 0x7FF60A500BB5 frame 0x00D5889FFB60 rva 0x000000320BB5 in Gw2-64
			ep 0x7FF60A4FEF40 frame 0x00D5889FFC10 rva 0x00000031EF40 in Gw2-64
			ep 0x7FF60A4FF041 frame 0x00D5889FFCB0 rva 0x00000031F041 in Gw2-64
			ep 0x7FF60A4FEB90 frame 0x00D5889FFD40 rva 0x00000031EB90 in Gw2-64
			ep 0x7FF60A4FFFB7 frame 0x00D5889FFD90 rva 0x00000031FFB7 in Gw2-64
			ep 0x7FF60A500086 frame 0x00D5889FFDC0 rva 0x000000320086 in Gw2-64
			ep 0x7FF60A4FE345 frame 0x00D5889FFDF0 rva 0x00000031E345 in Gw2-64
			ep 0x7FF60A2AFB2D frame 0x00D5889FFE20 rva 0x0000000CFB2D in Gw2-64
			ep 0x7FF60A4BAA20 frame 0x00D5889FFE50 rva 0x0000002DAA20 in Gw2-64
			ep 0x7FFCF53E7034 frame 0x00D5889FFE80 rva 0x000000017034 in KERNEL32
			ep 0x7FFCF7022651 frame 0x00D5889FFF00 rva 0x000000052651 in ntdll
			start 0x7FF60A4BA9D0 rva 0x0000002DA9D0 in Gw2-64

**Comment by Azuna1** [comment]
crash was related to special agent names
https://github.com/0x0ACB/gw2cc_private/commit/cc81a2fdf7569fc70855c278a1a5609f31ba07aa

**Comment by DatHacksGaming** [comment]
Tested with new update, crashes immediately upon signing into gw2co

[arcdps_lastcrash.log](https://github.com/Azuna1/gw2co-documentation/files/8364388/arcdps_lastcrash.log)
