### ISSUE TITLE
AbortAction 

### ISSUE THREAD

**Issue by DatHacksGaming** [Azuna1/gw2co-documentation#42]
Using Player:AbortAction() will result in being kicked to the character selection screen and this error

![image](https://user-images.githubusercontent.com/20995515/161145658-2d4da910-bc52-437a-93ce-9b414354cf01.png)

**Comment by Azuna1** [comment]
https://github.com/0x0ACB/gw2cc_private/commit/d93a5576665b6a35a0998eb07303adfc697b6536
