### ISSUE TITLE
Add combat statistics read out functionality.

### ISSUE THREAD

**Issue by blunderbusterboi** [Azuna1/gw2co-documentation#46]
We already have access to the following which could be used to determine damage or heals but more insight would be helpful to create a comprehensive DPS meter:
- Agent.barrier
- Agent.effects
- Agent.health

Add functionality to read out damage, heals, conditions and boons by all agents including the player. The below values would be a typically good start, this should be a new class that holds elements with agentId and a queue collection (limited dimension, FIFO) struct with the following properties:
- Damage taken
- Damage dealt
- Damage dealt by skillId
- Damage is a condition
- Damage applied to agentId array (for AoE)
- Heals applied
- Heals applied to agentId array (for AoE)

**Comment by DatHacksGaming** [comment]
Wouldn't this be just recreating arcDPS at that point though? That sounds awfully close to just creating a parser.

**Comment by DatHacksGaming** [comment]
I've never had an issue with arcDPS I've been using it with gw2co for a few weeks now. just gives a directX hook error click ok twice and then it retries and succeeds.

**Comment by Azuna1** [comment]
We have that info available I guess so shouldn't be to much of s task. 
IDK arcdps , can you modify/ create own UI stuff with the data?
