### ISSUE TITLE
Game client crash on entering WvW.

### ISSUE THREAD

**Issue by blunderbusterboi** [Azuna1/gw2co-documentation#47]
CTD on entering all worlds including EoTM with `Unknown Exception`

**Comment by DatHacksGaming** [comment]
I thought I already made this issue in #26

**Comment by Azuna1** [comment]
https://bit.ly/36M1jiF
fixed in next version

https://github.com/0x0ACB/gw2cc_private/commit/10b9cff7b69c1747a69a0664ef8844da9ed184c7
