### ISSUE TITLE
Game client stops rendering if CTRL+ALT+DEL is used to invoke the task manager.

### ISSUE THREAD

**Issue by blunderbusterboi** [Azuna1/gw2co-documentation#48]
Reproduce while in the world and gw2co is running: 

- Run game client windowed full screen or full screen.
- CTRL+ALT+DEL and open task manager or cancel.
- Note that game client stops rendering, however, still running.

**NOTES:** 
- ALT+ENTER can be used to switch render mode. 
- The UAC popup can also cause this.
- Locking the screen and unlocking can also cause this.

**Comment by Azuna1** [comment]
related https://github.com/Azuna1/gw2co-documentation/issues/40
