### ISSUE TITLE
Add slot number to the return value of Player:GetSkillbarSkills()

### ISSUE THREAD

**Issue by blunderbusterboi** [Azuna1/gw2co-documentation#51]
In addition to `skillId`, `cooldown`, `cooldownLeft`
Add `slotnumber` to indicate which `SKILLBARSLOT` the skill was cast

**Comment by Azuna1** [comment]
https://github.com/Azuna1/gw2co-documentation/wiki/Detail#skillcasting

**Comment by blunderbusterboi** [comment]
Ermahghards lol... thanks.
