### ISSUE TITLE
ImGui:ImageLoad not loading images.

### ISSUE THREAD

**Issue by blunderbusterboi** [Azuna1/gw2co-documentation#53]
`ImGui:ImageLoad` always returns an `ImageContainer` with result being false.

**HOW TO REPRODUCE THE ISSUE:**
- Place `guardian.png` and `guardian.jpg` in the game client's folder.
[guardian.jpg](https://user-images.githubusercontent.com/87025697/161974017-17283e7e-c3b2-40e2-88bd-104fff73d874.jpg)
[guardian.png](https://user-images.githubusercontent.com/87025697/161974023-56e39805-4c76-45f7-a8bd-8167d28762da.png)
- Create a `test.lua` with the below script and run.
- Additionally tried an absolute path to the image files with the result being the same.

```lua
local imageContainerPNG = ImGui:ImageLoad(".\\guardian.png")
local imageContainerJPG = ImGui:ImageLoad(".\\guardian.jpg")

function init()
    Info("INIT TEST")
    SetTickInterval(10000)
end

function tick()
end

function draw()
    if (imageContainerPNG.result) then
        if (ImGui:Begin("TEST WINDOW PNG", true, 0)) then
            ImGui:Image(imageContainerPNG.img, ImGui.ImVec2(120, 120))
            ImGui:End()
        end
    end

    if (imageContainerJPG.result) then
        if (ImGui:Begin("TEST WINDOW JPG", true, 0)) then
            ImGui:Image(imageContainerJPG.img, ImGui.ImVec2(120, 120))
            ImGui:End()
        end
    end
end
```

**Comment by Azuna1** [comment]
fixed with 0.2.127440+build.129

use this for relative path

```lua
imageContainerPNG= nil

function script_path()
   local str = debug.getinfo(2, "S").source:sub(2)
   return str:match("(.*/)")
end

function init()
    Info("INIT TEST")
    imageContainerPNG = ImGui:ImageLoad(script_path() .. "guardian.png")
end
```
