### ISSUE TITLE
Return player (self) skillbar info.

### ISSUE THREAD

**Issue by blunderbusterboi** [Azuna1/gw2co-documentation#54]
For the player character, provide access to list information about the player's skillbar.
A table of skillId and occupying slot is sufficient.

**Comment by Azuna1** [comment]
all info about your skillbar are currently available via API

**Comment by blunderbusterboi** [comment]
This is true for `Player.GetSkillbarSkills()` and combined with `Agent.casting` the skill bar can be detected which requires some priming by using the skills once.

This issue request is to have a function exposed that does not need priming to return information about the skill bar.

**Comment by Azuna1** [comment]
this wont be part of the API
however you could search for the skillbar info in memory using https://github.com/Azuna1/gw2co-documentation/wiki/Memory
