### ISSUE TITLE
Agent.profession is always zero in the Detail:GetAllAgents() result set.

### ISSUE THREAD

**Issue by blunderbusterboi** [Azuna1/gw2co-documentation#55]
Affected release `0.2.127440+build.138.64da`

`Agent.profession` is always zero in the `Detail:GetAllAgents()` result set.

Expecting it to be a number correlating to the [PROFESSION](https://github.com/Azuna1/gw2co-documentation/wiki/Globals#profession) enum.

Use the below script in an area with players and observe the output. The player name and an integer value corresponding to their profession is displayed but this value is always zero.

```lua
function init()
    Info("INIT TEST")
    SetTickInterval(5000)
end

function tick()
    local allAgents = Detail:GetAllAgents()
    if (allAgents ~= nil) then
        for agentId, agentInstance in pairs(allAgents) do
            if (agentInstance.type == AGENT_TYPE.AGENT_TYPE_PLAYER) then
                Info(agentInstance.name .. " " .. agentInstance.profession)
            end
        end
    end
end

function draw()
end
```

**Comment by Azuna1** [comment]
https://github.com/0x0ACB/gw2cc_private/commit/8c3cece1153e2313bf2ace642164e6a00abd1688
