### ISSUE TITLE
Agent_Type not lining up with wiki info

### ISSUE THREAD

**Issue by DatHacksGaming** [Azuna1/gw2co-documentation#56]
On the wiki it shows AGENT_TYPE_PLAYER as the 6th option meaning it should be type 5. I've also noticed a missing type 10 which is things you can interact with like WvW capture zones, Supplies in WvW, mining nodes, vistas etc.

Seen players showing as 0 and 255 but never 5.

![image](https://user-images.githubusercontent.com/20995515/162339954-215b1dd9-0811-4dff-aeb8-f5b4c3170fc1.png)

**Comment by Azuna1** [comment]
That is exactly why you should use the enum representation instead of the number 😊
Enums don't necessarily are in a straight linear order

**Comment by DatHacksGaming** [comment]
Ah thought you were doing them in order like that I use the Enums this is just what they are returning as values :) not sure what the type 10 is, that could be considered Gadgets.

**Comment by 0x0ACB** [comment]
```   
    enum Type
    {
        AGENT_TYPE_CHARACTER,
        AGENT_TYPE_COMBATANT,
        AGENT_TYPE_GADGET = 10,
        AGENT_TYPE_GADGET_ATTACK_TARGET = 11,
        AGENT_TYPE_ITEM = 15
    };
```
