### ISSUE TITLE
Mechanist Profession Skills work different than other classes

### ISSUE THREAD

**Issue by DatHacksGaming** [Azuna1/gw2co-documentation#58]
Tested with Dragonhunter and it works however Mechanist seems to function differently 
Profession skills for F1-F5 are based on what they refer to as Tool Belt Skills and they have no Slot ID in the API Same with the other abilities. Possibly just needs the packet added for these?

Example Explosive Knuckle
https://api.guildwars2.com/v2/skills?ids=63365&lang=en

        Player:UseSkillbarSkill(SKILLBARSLOT.SKILLBARSLOT_PROF_1,44364,myId) --dragonhunter F1 (works)

        Player:UseSkillbarSkill(SKILLBARSLOT.SKILLBARSLOT_PROF_1,63365,PLocked.id) --mechanist f1 Explosive Knuckle (does nothing)

**Comment by bulllit** [comment]
yes, it will be the same for rangerpets. for now you can "spamm" keypresses to activate them

**Comment by DatHacksGaming** [comment]
Yeah I have it using Detail:SimulateKeyPress(0x3b) for the time being haha but that gets REALLY messy with functions and you can't alt tab then haha

**Comment by Azuna1** [comment]
fixed / added in upcoming release 
Player:PetAction
https://github.com/0x0ACB/gw2cc_private/commit/ac371cb5c340c522bf331357e6b3dbaaf2542c95
