### ISSUE TITLE
DEAD_STATE not returning correct values

### ISSUE THREAD

**Issue by DatHacksGaming** [Azuna1/gw2co-documentation#60]
Enums for DEAD_STATE not working as intended.
Using the ESP you can see the DEAD_STATE as a number.

Testing with code when using 

If Target.deadState ~= DEAD_STATE_DEAD then Player:UseSkillbarSkill...
it should do the action as long as the agent target is not dead, however it continues to attack the dead target. If you change the Enum to 1 (the value of dead.State as DEAD) then it'll work and ignore the dead body. 
Same with DOWNED == 2 but the Enum isn't returning them in the downed state.

  DEAD_STATE_ALIVE
  DEAD_STATE_DEAD
  DEAD_STATE_DOWNED

**Comment by Ops226** [comment]
That'd be the wrong usage of it that's why :(

try Target.deadState ~= DEAD_STATE.DEAD_STATE_DOWNED
